Stack-Knowledge/Stack-Knowledge-Server

src/main/kotlin/com/stack/knowledege/global/error/handler/GlobalExceptionHandler.kt
exception handler 카멜로 변경
exception handler 카멜로 변경했습니다.
e.errorCode가 재사용이 되어 변수로 빼서 사용했지만, kotlin 스럽게 짜고 싶어 변경했습니다.
=> # 41 exception handler 카멜로 변경

src/main/kotlin/com/stack/knowledege/domain/auth/application/spi/GAuthPort.kt, src/main/kotlin/com/stack/knowledege/domain/auth/application/usecase/GAuthSignInUseCase.kt, src/main/kotlin/com/stack/knowledege/thirdparty/aws/s3/AwsS3Adapter.kt, src/main/kotlin/com/stack/knowledege/thirdparty/aws/s3/config/AwsS3Config.kt, src/main/kotlin/com/stack/knowledege/thirdparty/aws/s3/config/properties/AwsS3Properties.kt, src/main/kotlin/com/stack/knowledege/thirdparty/gauth/GAuthAdapter.kt, src/main/kotlin/com/stack/knowledege/thirdparty/gauth/config/GAuthConfig.kt, src/main/kotlin/com/stack/knowledege/thirdparty/gauth/properties/GAuthProperties.kt
GAuth port 위치 변경
GAuth port 위치를 변경했습니다.
config, properties 를 패키지를 만들어 위치시켰습니다.
=> # 43 GAuth port 위치 변경

src/main/kotlin/com/stack/knowledege/domain/mission/exception/AlreadySolvedMissionException.kt
=> # 45 사용하지 않는 exception 삭제

src/main/kotlin/com/stack/knowledege/domain/image/application/usecase/UpdateImageUseCase.kt, src/main/kotlin/com/stack/knowledege/domain/image/application/usecase/UploadImageUseCase.kt, src/main/kotlin/com/stack/knowledege/domain/mission/application/scheduler/MissionScheduler.kt, src/main/kotlin/com/stack/knowledege/domain/mission/application/spi/QueryMissionPort.kt, src/main/kotlin/com/stack/knowledege/domain/mission/application/usecase/QueryAllMissionUseCase.kt, src/main/kotlin/com/stack/knowledege/domain/mission/persistence/MissionPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledege/domain/mission/persistence/mapper/MissionMapper.kt, src/main/kotlin/com/stack/knowledege/domain/order/application/spi/QueryOrderPort.kt, src/main/kotlin/com/stack/knowledege/domain/order/persistence/OrderPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledege/domain/student/exception/StudentNotFoundException.kt, src/main/kotlin/com/stack/knowledege/domain/student/presentation/data/response/StudentResponse.kt
전체적인 컨벤션 맞추기
전체적인 컨벤션을 맞추었습니다.
사용하지 않는 메서드를 삭제하였습니다.
=> # 57 전체적인 컨벤션 맞추기

src/main/kotlin/com/stack/knowledege/domain/solve/application/spi/CommandSolvePort.kt, src/main/kotlin/com/stack/knowledege/domain/solve/application/spi/QuerySolvePort.kt, src/main/kotlin/com/stack/knowledege/domain/solve/application/usecase/SolveMissionUseCase.kt, src/main/kotlin/com/stack/knowledege/domain/solve/exception/AlreadySolvedException.kt, src/main/kotlin/com/stack/knowledege/domain/solve/persistence/SolvePersistenceAdapter.kt, src/main/kotlin/com/stack/knowledege/domain/solve/persistence/repository/SolveJpaRepository.kt, src/main/kotlin/com/stack/knowledege/global/error/ErrorCode.kt, src/main/kotlin/com/stack/knowledege/global/security/SecurityConfig.kt
save에 반환 값 추가
save에 반환 값을 추가하였습니다.
이미 푼 문제에 대해 예외처리를 해주었습니다.
=> # 59 save에 반환 값 추가

src/main/kotlin/com/stack/knowledege/domain/item/application/usecase/QueryAllItemUseCase.kt, src/main/kotlin/com/stack/knowledege/domain/item/domain/Item.kt, src/main/kotlin/com/stack/knowledege/domain/item/persistence/entity/ItemJpaEntity.kt, src/main/kotlin/com/stack/knowledege/domain/item/persistence/mapper/ItemMapper.kt, src/main/kotlin/com/stack/knowledege/domain/item/presentation/data/response/ItemResponse.kt, src/main/kotlin/com/stack/knowledege/domain/order/application/usecase/QueryIsOrderedOrderUseCase.kt, src/main/kotlin/com/stack/knowledege/domain/point/application/spi/QueryPointPort.kt, src/main/kotlin/com/stack/knowledege/domain/point/persistence/PointPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledege/domain/point/persistence/repository/PointJpaRepository.kt, src/main/kotlin/com/stack/knowledege/domain/solve/application/usecase/SolveMissionUseCase.kt, src/main/kotlin/com/stack/knowledege/domain/user/application/usecase/ScoreSolveUseCase.kt
item image 필드 추가
item image 필드를 추가하였습니다.
point 가 겹치는 오류를 해결하였습니다.
=> # 60 item image 필드 추가

src/main/resources/application.yml
maria db driver 설정
maria db driver 설정해줬습니다.
=> # 63 maria db driver 설정

src/main/resources/application.yml
=> # 64 mariadb url 변경

src/main/kotlin/com/stack/knowledge/global/health/HealthCheckWebAdapter.kt
=> # 65 health check

src/main/kotlin/com/stack/knowledge/domain/solve/application/spi/QuerySolvePort.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/SolvePersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/repository/SolveJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/usecase/QueryScoringPageUseCase.kt, src/main/kotlin/com/stack/knowledge/global/security/SecurityConfig.kt
채점 페이지 페이징 처리
채점 페이지에 페이징을 적용했습니다.
=> # 66 채점 페이지 페이징 처리

src/main/kotlin/com/stack/knowledge/common/service/impl/SecurityServiceImpl.kt, src/main/kotlin/com/stack/knowledge/global/filter/ExceptionFilter.kt
Student Exception
UserNotFoundException -> StudentNotFoundException
internal server error 주석을 삭제했습니다.
=> # 70 Student Exception

src/main/kotlin/com/stack/knowledge/thirdparty/gauth/GAuthAdapter.kt, src/main/kotlin/com/stack/knowledge/thirdparty/gauth/config/GAuthConfig.kt
=> # 70 gAuth 카멜케이스로 변경

src/main/kotlin/com/stack/knowledge/domain/student/application/usecase/QueryStudentPointInfoUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/student/presentation/StudentWebAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/student/presentation/data/response/StudentPointResponse.kt, src/main/kotlin/com/stack/knowledge/domain/student/presentation/data/response/StudentResponse.kt, src/main/kotlin/com/stack/knowledge/global/security/SecurityConfig.kt
내 랭킹 정보 조회
학생 포인트 랭킹 조회 api로 해결할 수 없는 문제를 내 랭킹 정보 조회 api를 하나 더 만들어 해결하였습니다.
=> # 73 내 랭킹 정보 조회

src/main/kotlin/com/stack/knowledge/global/security/SecurityConfig.kt
전체적인 접근권한 수정
전체적으로 api 별 접근권한을 수정해주었습니다.
=> # 74 전체적인 접근권한 수정

src/main/kotlin/com/stack/knowledge/global/config/WebMvcConfig.kt
WebMvcConfig 적용
WebMvcConfigurer을 상속받은 WebMvcConfig 클래스를 만들어 cors를 방지했습니다.
=> # 75 WebMvcConfig 적용

src/main/kotlin/com/stack/knowledge/global/filter/ExceptionFilter.kt
exception filter 500 에러 log
exception filter 500 에러 log 찍어주기
=> # 76 exception filter 500 에러 log

src/main/kotlin/com/stack/knowledge/domain/auth/presentation/AuthWebAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/auth/presentation/data/request/GAuthSignInRequest.kt
valid annotation 삭제
valid annotation 삭제
=> # 77 valid annotation 삭제

src/main/kotlin/com/stack/knowledge/domain/auth/application/usecase/ReissueTokenUseCase.kt
토큰 재발급 오류 수정
토큰 재발급에서 authority때문에 발생하는 오류를 수정하였습니다.
=> # 78 토큰 재발급 오류 수정

src/main/kotlin/com/stack/knowledge/global/security/SecurityConfig.kt
=> # 79 접근권한 모두 허용

src/main/kotlin/com/stack/knowledge/domain/student/application/usecase/QueryAllStudentsRankingUseCase.kt, src/main/resources/application.yml
전체 학생 랭킹 조회 수정
전체 학생 랭킹 조회 오류를 수정하였습니다.
=> # 80 전체 학생 랭킹 조회 수정

src/main/kotlin/com/stack/knowledge/domain/user/application/usecase/QueryScoringPageUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/user/presentation/UserWebAdapter.kt
페이징 처리 수정
페이징 처리를 1페이지만 하고 있던 이슈를 수정하였습니다.
=> # 82 페이징 처리 수정

src/main/kotlin/com/stack/knowledge/domain/user/application/usecase/QueryScoringPageUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/user/presentation/data/response/AllScoringResponse.kt
채점 페이지 response 값 수정
채점 페이지 response 값에 title이 빠져있어 수정해주었습니다.
=> # 83 채점 페이지 response 값 수정

src/main/kotlin/com/stack/knowledge/domain/mission/application/scheduler/MissionScheduler.kt, src/main/kotlin/com/stack/knowledge/domain/mission/application/usecase/CreateMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/user/presentation/UserWebAdapter.kt, src/main/kotlin/com/stack/knowledge/global/security/SecurityConfig.kt
개발에 방해되는 코드 주석 처리
프로젝트 특성 상 Mission은 특정 시간에만 제어할 수 있습니다. 특정 시간에만 작업해야하는 불편함을 해소하고자 주석처리 하였습니다.
=> # 84 개발에 방해되는 코드 주석 처리

src/main/kotlin/com/stack/knowledge/global/filter/JwtRequestFilter.kt, src/main/kotlin/com/stack/knowledge/global/security/SecurityConfig.kt, src/main/resources/application.yml
Spring Security Except
`/auth/**` url의 api를 spring security가 적용되지 않게 설정해주었습니다.
이유는 `/auth/**` url을 가진 api는 token을 담은 요청이 왔을 때 오류가 터질 수 있기 때문에 jwt request filter 가 적용되지 않게 수정했습니다.
=> # 86 Spring Security Except

src/main/kotlin/com/stack/knowledge/global/filter/ExceptionFilter.kt, src/main/resources/application.yml
exception throw 하는 설정 추가
exception throw가 안되는 이슈가 발생해 exception을 throw 해주는 설정을 추가 해주었습니다.
=> # 87 exception throw 하는 설정 추가

src/main/kotlin/com/stack/knowledge/global/filter/ExceptionFilter.kt, src/main/kotlin/com/stack/knowledge/global/filter/JwtRequestFilter.kt, src/main/kotlin/com/stack/knowledge/global/security/SecurityConfig.kt
auth url ignore 주석
auth 도메인 url ignore 처리를 해둔 설정 코드를 주석 처리 해주었습니다.
=> # 88 auth url ignore 주석

src/main/kotlin/com/stack/knowledge/domain/item/application/usecase/QueryAllItemUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/item/presentation/data/response/ItemResponse.kt, src/main/kotlin/com/stack/knowledge/domain/order/application/usecase/QueryIsOrderedOrderUseCase.kt
Response dto id 일관성 맞추기
Response dto에서 id 일관성 맞추어 주었습니다.
=> # 90 Response dto id 일관성 맞추기

src/main/kotlin/com/stack/knowledge/domain/auth/application/usecase/GAuthSignInUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/order/application/usecase/OrderItemUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/usecase/SolveMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/student/application/spi/QueryStudentPort.kt, src/main/kotlin/com/stack/knowledge/domain/student/application/usecase/QueryStudentPointInfoUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/student/persistence/StudentPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/student/persistence/repository/StudentJpaRepository.kt
Student 조회 인자 값 수정
Student 를 조회할 때 user를 넣어줘야 하지만 student를 넣어주어서 인자 값을 수정해주었습니다.
=> # 91 Student 조회 인자 값 수정

src/main/kotlin/com/stack/knowledge/domain/user/presentation/UserWebAdapter.kt, src/main/kotlin/com/stack/knowledge/global/security/SecurityConfig.kt
겹치는 url 수정
url 이 겹쳐서 일어나는 이슈를 해결하였습니다.
=> # 93 겹치는 url 수정

src/main/kotlin/com/stack/knowledge/domain/image/application/usecase/UploadImageUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/solve/exception/AlreadySolvedException.kt, src/main/kotlin/com/stack/knowledge/domain/user/exception/ProfileImageNotFoundException.kt, src/main/kotlin/com/stack/knowledge/global/error/ErrorCode.kt
null 을 "" 로 치환
처음 회원가입할 때 유저의 프로필 이미지를 ""로 주어서 프로필 이미지가 삭제 되지 않던 문제를 ""로 치환하여 고쳐주었습니다.
=> # 95 null 을 "" 로 치환

src/main/kotlin/com/stack/knowledge/domain/student/presentation/StudentWebAdapter.kt
RequestPart required 변경
RequestPart required에 대해 자세히 알지 못하고 구글링으로 오류 해결법만 찾아본 것이 문제가 되었습니다.
다시 요구사항에 맞게 `required = false`를 삭제해주었습니다.
=> # 97 RequestPart required 변경

src/main/kotlin/com/stack/knowledge/domain/student/presentation/StudentWebAdapter.kt, src/main/kotlin/com/stack/knowledge/global/security/SecurityConfig.kt
RequestPart를 RequestParam으로 변경
RequestPart를 RequestParam으로 변경해주었습니다.
글을 읽던 중 단일 multiPartFile일 땐 RequestParam이 좋다는 글이 있어 변경해주었습니다.
또한 예전에 설정해놓은 http ignore 주석을 삭제했습니다.
=> # 98 RequestPart를 RequestParam으로 변경

src/main/kotlin/com/stack/knowledge/global/config/WebMvcConfig.kt
cors domain 추가
vercel admin 도메인을 cors 가 발생하지 않게 처리해주었습니다.
=> # 99 cors domain 추가

src/main/kotlin/com/stack/knowledge/domain/image/application/spi/ImagePort.kt, src/main/kotlin/com/stack/knowledge/domain/image/application/spi/QueryImagePort.kt, src/main/kotlin/com/stack/knowledge/domain/image/application/usecase/UploadImageUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/user/exception/ProfileImageNotFoundException.kt, src/main/kotlin/com/stack/knowledge/global/error/ErrorCode.kt, src/main/kotlin/com/stack/knowledge/thirdparty/aws/s3/AwsS3Adapter.kt
image 저장 형식 변경
queryImagePort를 삭제하였습니다.
queryImageUrl 함수 Private 함수로 변경해주었습니다.
user save에서 User 리턴을 받아 profileImage를 반환해주었습니다.
=> # 100 image 저장 형식 변경

src/main/kotlin/com/stack/knowledge/domain/student/presentation/StudentWebAdapter.kt
RequestPart 로 변경
RequestParam 을 RequestPart 로 변경해주었습니다.
=> # 102 RequestPart 로 변경

src/main/kotlin/com/stack/knowledge/global/config/WebMvcConfig.kt
Client domain url cors 오류 수정
`https://stack-knowledge-client.vercel.app/**` 로 cors 설정 변경해주었습니다.
=> # 103 Client domain url cors 오류 수정

src/main/kotlin/com/stack/knowledge/domain/student/application/usecase/QueryStudentPointInfoUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/student/presentation/data/response/StudentPointResponse.kt
MyPage Response 에 현재 점수 추가
현재 포인트 조회 api 가 추가로 필요한 상황에서 MyPage 에 현재 점수까지 Response 에 추가해줘서 API를 추가하는 대신 Response에 추가해주었습니다.
=> # 104 MyPage Response 에 현재 점수 추가

src/main/kotlin/com/stack/knowledge/global/error/handler/GlobalExceptionHandler.kt
Valid, Json 관련 Exception Handle
`Valid` 어노테이션에서 걸러지는 오류들을 handle 하도록 설정했습니다.
예를 들어 `Json` 형식이 아닌 `Text`로 요청이 오는 Exception을 handle 하도록 설정했습니다.
=> # 105 Valid, Json 관련 Exception Handle

src/main/kotlin/com/stack/knowledge/domain/mission/application/spi/QueryMissionPort.kt, src/main/kotlin/com/stack/knowledge/domain/mission/persistence/MissionPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/mission/persistence/repository/MissionJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/spi/QuerySolvePort.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/SolvePersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/repository/SolveJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/usecase/QueryScoringPageUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/user/presentation/UserWebAdapter.kt
채점 페이지 자신이 등록한 문제만 볼 수 있게 변경
원래 다른 선생님이 등록한 문제의 풀이까지 볼 수 있었지만 자신이 등록한 문제 풀이만 조회할 수 있게 변경하였습니다.
=> # 107 채점 페이지 자신이 등록한 문제만 볼 수 있게 변경

src/main/kotlin/com/stack/knowledge/domain/mission/application/usecase/QueryAllMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/order/application/spi/QueryOrderPort.kt, src/main/kotlin/com/stack/knowledge/domain/order/application/usecase/OrderItemUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/order/persistence/OrderPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/order/persistence/repository/OrderJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/spi/QuerySolvePort.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/usecase/SolveMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/SolvePersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/repository/SolveJpaRepository.kt, src/main/resources/application.yml
전체 문제 조회 수정, 아이템 주문 수정
전체 문제를 조회할 때 이미 푼 문제도 조회되는 이슈가 발생해 수정해 주었습니다.
`queryAll` 을 사용해주지 않아 생기던 이슈를 수정해 주었습니다.
=> # 108 전체 문제 조회 수정, 아이템 주문 수정

src/main/kotlin/com/stack/knowledge/global/security/SecurityConfig.kt
Any request permit all
핸들하지 않는 url 의 접근권한을 permit all 로 변경해주었습니다.
=> # 112 Any request permit all

src/main/kotlin/com/stack/knowledge/domain/mission/application/spi/QueryMissionPort.kt, src/main/kotlin/com/stack/knowledge/domain/mission/application/usecase/QueryAllMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/mission/persistence/MissionPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/mission/persistence/repository/MissionJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/order/application/spi/QueryOrderPort.kt, src/main/kotlin/com/stack/knowledge/domain/order/application/usecase/QueryIsOrderedOrderUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/order/persistence/OrderPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/order/persistence/repository/OrderJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/spi/QuerySolvePort.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/SolvePersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/repository/SolveJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/usecase/QueryScoringPageUseCase.kt
전체 조회 API 정렬
전체 조회 관련 API를 생성된 시간 순으로 정렬 시켜주었습니다.
=> # 114 전체 조회 API 정렬

src/main/kotlin/com/stack/knowledge/domain/auth/presentation/AuthWebAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/auth/presentation/data/request/GAuthSignInRequest.kt, src/main/kotlin/com/stack/knowledge/domain/item/application/usecase/QueryAllItemUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/mission/application/usecase/QueryAllMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/mission/presentation/data/request/CreateMissionRequest.kt, src/main/kotlin/com/stack/knowledge/domain/order/application/usecase/OrderItemUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/order/presentation/OrderWebAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/order/presentation/data/request/OrderItemRequest.kt, src/main/kotlin/com/stack/knowledge/domain/order/presentation/data/request/UpdateOrderRequest.kt, src/main/kotlin/com/stack/knowledge/domain/point/persistence/repository/PointJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/spi/QuerySolvePort.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/usecase/SolveMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/SolvePersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/repository/SolveJpaRepository.kt
미션 풀기 포인트 지급 이슈 수정
find 메서드를 exist 로 변경해주었습니다.
Valid annotation을 추가해주었습니다.
포인트가 존재하지 않을 때 기본 포인트를 1000으로 설정해주었습니다.
=> # 115 미션 풀기 포인트 지급 이슈 수정

src/main/kotlin/com/stack/knowledge/domain/mission/application/spi/QueryMissionPort.kt, src/main/kotlin/com/stack/knowledge/domain/mission/application/usecase/QueryAllMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/mission/persistence/MissionPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/mission/persistence/repository/MissionJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/order/persistence/OrderPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/order/persistence/repository/OrderJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/spi/QuerySolvePort.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/SolvePersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/repository/SolveJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/usecase/QueryScoringPageUseCase.kt
최근 순으로 정렬
createdAt 을 이용한 정렬을 최근 순으로 정렬이 되게 변경해주었습니다.
=> # 116 최근 순으로 정렬

src/main/kotlin/com/stack/knowledge/domain/image/application/usecase/UploadImageUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/usecase/SolveMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/global/config/WebMvcConfig.kt
Cors 도메인 url 변경
도메인 url 이 변경되어 cors 설정 url 을 변경해주었습니다.
=> # 117 Cors 도메인 url 변경

src/main/kotlin/com/stack/knowledge/domain/mission/application/usecase/QueryMissionDetailsUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/usecase/SolveMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/time/persistence/repository/TimeJpaRepository.kt, src/main/kotlin/com/stack/knowledge/global/error/ErrorCode.kt, src/main/kotlin/com/stack/knowledge/global/error/ErrorResponse.kt, src/main/kotlin/com/stack/knowledge/global/filter/ExceptionFilter.kt
Time query 핫픽스
findByMissionJpaEntity 메서드가 nullable 한 MissionJpaEntity를 반환하도록 변경해주었습니다.
=> # 121 Time query 핫픽스

src/main/kotlin/com/stack/knowledge/domain/solve/application/usecase/SolveMissionUseCase.kt
save solve 순서 변경
save solve 순서 변경를 변경하여 mission 전체 조회할 때 안보이게 수정해주었습니다.
=> # 122 save solve 순서 변경

src/main/kotlin/com/stack/knowledge/domain/solve/presentation/data/request/SolveMissionRequest.kt
solvation 제출 notnull로 변경
solvation 제출할 때  Valid annotation을 notBlank에서 notNull로 변경해 주었습니다.
=> # 123 solvation 제출 notnull로 변경

src/main/kotlin/com/stack/knowledge/domain/mission/application/usecase/QueryMissionDetailsUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/solve/presentation/SolveWebAdapter.kt, src/main/kotlin/com/stack/knowledge/global/security/SecurityConfig.kt
Security Config 접근권한 주석 제거
Security Config 클래스의 접근권한을 설정해주는 코드의 주석을 제거
=> # 124 Security Config 접근권한 주석 제거

build.gradle.kts, src/main/kotlin/com/stack/knowledge/domain/auth/application/spi/CommandRefreshTokenPort.kt, src/main/kotlin/com/stack/knowledge/domain/auth/application/usecase/ReissueTokenUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/auth/persistence/RefreshTokenPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/item/application/spi/QueryItemPort.kt, src/main/kotlin/com/stack/knowledge/domain/mission/application/spi/QueryMissionPort.kt, src/main/kotlin/com/stack/knowledge/domain/mission/application/usecase/CreateMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/mission/application/usecase/QueryMissionDetailsUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/mission/persistence/MissionPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/mission/persistence/entity/MissionJpaEntity.kt, src/main/kotlin/com/stack/knowledge/domain/mission/persistence/repository/MissionJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/mission/presentation/MissionWebAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/order/application/spi/QueryOrderPort.kt, src/main/kotlin/com/stack/knowledge/domain/order/application/usecase/OrderItemUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/order/application/usecase/QueryIsOrderedOrderUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/order/persistence/OrderPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/order/persistence/entity/OrderJpaEntity.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/usecase/SolveMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/student/application/spi/QueryStudentPort.kt, src/main/kotlin/com/stack/knowledge/domain/student/application/usecase/QueryAllStudentsRankingUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/student/application/usecase/QueryStudentPointInfoUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/student/persistence/StudentPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/student/persistence/repository/StudentJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/time/persistence/entity/TimeJpaEntity.kt, src/main/kotlin/com/stack/knowledge/domain/time/persistence/repository/TimeJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/usecase/QueryScoringPageUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/usecase/ScoreSolveUseCase.kt, src/main/kotlin/com/stack/knowledge/global/filter/ExceptionFilter.kt
N + 1 이슈 해결
fetch type이 Lazy가 아닌 entity를 Lazy로 변경해주었습니다.
token refresh 로직에서 전에 쓰던 token 을 삭제해 redis 의 효율을 높였습니다.
Query annotation 과 entity graph를 이용해 성능을 개선했습니다.
kotlin dsl 을 이용해 코드를 개선했습니다.
=> # 125 N + 1 이슈 해결

src/main/kotlin/com/stack/knowledge/domain/solve/application/spi/QuerySolvePort.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/usecase/SolveMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/SolvePersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/repository/SolveJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/time/persistence/entity/TimeJpaEntity.kt
미션 풀이 서비스 수정
mission : time = 1 : 1 로 연관관계를 수정해주었습니다.
solveMissionUsecase에 `noRollbackFor = [TimeLimitExceededException::class]` 로 설정해주었습니다.
=> # 126 미션 풀이 서비스 수정

src/main/kotlin/com/stack/knowledge/domain/solve/application/usecase/SolveMissionUseCase.kt
미션 풀이 시간 수정
미션 풀이 시간에 2초를 추가해주어 안전하게 처리했습니다.
=> # 127 미션 풀이 시간 수정

src/main/kotlin/com/stack/knowledge/domain/order/application/usecase/UpdateOrderUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/usecase/SolveMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/global/security/token/JwtGeneratorAdapter.kt
시간 초과 타임 설정 수정
3초를 추가로 주던 것을 5초로 수정해주었습니다.
=> # 128 시간 초과 타임 설정 수정

src/main/kotlin/com/stack/knowledge/domain/mission/application/usecase/QueryMissionDetailsUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/usecase/SolveMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/time/application/spi/QueryTimePort.kt, src/main/kotlin/com/stack/knowledge/domain/time/domain/Time.kt, src/main/kotlin/com/stack/knowledge/domain/time/persistence/TimePersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/time/persistence/entity/TimeJpaEntity.kt, src/main/kotlin/com/stack/knowledge/domain/time/persistence/mapper/TimeMapper.kt, src/main/kotlin/com/stack/knowledge/domain/time/persistence/repository/TimeJpaRepository.kt
time entity student 와 연관관계 추가
time : student = N : 1 로 설정해주어 solve mission 하는 데 생기는 이슈를 해결해주었습니다.
=> # 129 time entity student 와 연관관계 추가

src/main/kotlin/com/stack/knowledge/domain/point/application/spi/QueryPointPort.kt, src/main/kotlin/com/stack/knowledge/domain/point/persistence/PointPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/point/persistence/repository/PointJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/usecase/SolveMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/usecase/ScoreSolveUseCase.kt
mission point 최저점 조회
mission point 최고점 조회하던 것을 최저점을 조회하여 이슈를 해결하였습니다.
=> # 130 mission point 최저점 조회

src/main/kotlin/com/stack/knowledge/domain/mission/application/spi/QueryMissionPort.kt, src/main/kotlin/com/stack/knowledge/domain/mission/application/usecase/QueryAllMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/mission/persistence/MissionPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/mission/persistence/repository/MissionJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/usecase/SolveMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/usecase/QueryScoringPageUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/usecase/ScoreSolveUseCase.kt
채점 후 저장되는 Mission point 변경
채점 후 저장되는 Mission point 를 제일 낮은 점수의 mission point 로 변경하였습니다.
=> # 131 채점 후 저장되는 Mission point 변경

src/main/resources/application.yml
=> # 132 DB URL 관리 환경변수로 변경

src/main/kotlin/com/stack/knowledge/domain/image/application/usecase/UploadImageUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/spi/QueryUserPort.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/usecase/QueryScoringPageUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/user/persistence/UserPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/global/error/handler/GlobalExceptionHandler.kt, src/main/kotlin/com/stack/knowledge/global/filter/ExceptionFilter.kt, src/main/kotlin/com/stack/knowledge/global/security/principal/StudentDetailsService.kt, src/main/kotlin/com/stack/knowledge/global/security/principal/TeacherDetailsService.kt
Exception log 추가
Exception log를 추가해주었습니다.
UserDetailsService 구현 부에서 사용하지 않는 rollback 을 삭제해주었습니다.
=> # 134 Exception log 추가

src/main/kotlin/com/stack/knowledge/domain/solve/application/usecase/SolveMissionUseCase.kt
필요없는 변수 선언하지 않고 바로 exception throw 하게 변경
isExceeded 변수를 사용하지 않고 바로 throw 하게 변경해주었습니다.
=> # 136 필요없는 변수 선언하지 않고 바로 exception throw 하게 변경

src/main/kotlin/com/stack/knowledge/global/config/FilterConfig.kt, src/main/kotlin/com/stack/knowledge/global/filter/ExceptionFilter.kt, src/main/kotlin/com/stack/knowledge/global/filter/JwtRequestFilter.kt, src/main/kotlin/com/stack/knowledge/global/filter/RequestLogFilter.kt
Request Log Filter 구현
ip, method, url, response status 를 로깅하는 request log filter 를 구현하였습니다.
또한 Filter Config 클래스에 등록하여 동작하도록 만들어 주었습니다.
=> # 139 Request Log Filter 구현

src/main/kotlin/com/stack/knowledge/domain/auth/application/usecase/GAuthSignInUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/mission/application/usecase/QueryAllMissionUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/order/application/usecase/QueryIsOrderedOrderUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/student/application/usecase/QueryAllStudentsRankingUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/student/application/usecase/QueryStudentPointInfoUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/usecase/QueryScoringPageUseCase.kt, src/main/kotlin/com/stack/knowledge/domain/user/presentation/data/response/UserResponse.kt, src/main/kotlin/com/stack/knowledge/global/config/EnableSchedulingConfig.kt, src/main/kotlin/com/stack/knowledge/global/error/ErrorCode.kt, src/main/kotlin/com/stack/knowledge/global/filter/JwtRequestFilter.kt, src/main/kotlin/com/stack/knowledge/global/security/token/JwtParserAdapter.kt
필요없는 response 값 삭제
공통으로 사용되는 UserResponse class 의 email 프로퍼티를 삭제 해주었습니다.
또한 스케줄링 설정 클래스를 주석 처리 해주었습니다.
=> # 140 필요없는 response 값 삭제

src/main/kotlin/com/stack/knowledge/domain/auth/presentation/AuthWebAdapter.kt
logout return type 수정
Logout return type 이 Valid 였던 것을 Void 로 수정 해주었습니다.
=> # 143 logout return type 수정

src/main/kotlin/com/stack/knowledge/domain/auth/application/service/GoogleTeacherSignInService.kt, src/main/kotlin/com/stack/knowledge/domain/auth/exception/NotApprovedUserException.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/service/UpdateUserApproveStatusService.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/spi/CommandUserPort.kt, src/main/kotlin/com/stack/knowledge/domain/user/exception/AlreadyApprovedUserException.kt, src/main/kotlin/com/stack/knowledge/domain/user/persistence/UserPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/user/presentation/UserWebAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/user/presentation/data/request/UpdateUserApproveStatusRequest.kt, src/main/kotlin/com/stack/knowledge/global/error/ErrorCode.kt, src/main/kotlin/com/stack/knowledge/global/security/SecurityConfig.kt
User ApproveStatus Update 기능 구현
선생님 sign in 서비스에 pending 일 때 excpetion 을 throw 하는 로직을 추가 해주었습니다.
유저 approve status 를 변경해주는 서비스를 개발 하였습니다.
=> # 147 User ApproveStatus Update 기능 구현

src/main/kotlin/com/stack/knowledge/domain/auth/application/service/GAuthSignInService.kt, src/main/kotlin/com/stack/knowledge/domain/auth/application/service/GoogleStudentSignInService.kt, src/main/kotlin/com/stack/knowledge/domain/student/application/service/CreateStudentService.kt, src/main/kotlin/com/stack/knowledge/domain/student/application/spi/CommandStudentPort.kt, src/main/kotlin/com/stack/knowledge/domain/student/persistence/StudentPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/global/filter/ExceptionFilter.kt
Google Auth 핫픽스
Google login service에서 token을 발급할 때 student id 가 아닌 user id로 token을 발급해서 생기는 이슈를 해결 하였습니다.
=> # 149 Google Auth 핫픽스

src/main/kotlin/com/stack/knowledge/domain/auth/presentation/AuthWebAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/mission/presentation/MissionWebAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/order/presentation/OrderWebAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/solve/presentation/SolveWebAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/user/presentation/UserWebAdapter.kt
반환 타입 변경
코틀린 언어에 더 자연스럽게 반환타입을 Void에서 Unit으로 변경 해주었습니다.
=> # 151 반환 타입 변경

src/main/kotlin/com/stack/knowledge/domain/auth/application/service/GoogleTeacherSignInService.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/service/QueryAllSignUpRequestedTeacherService.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/service/UpdateUserApproveStatusService.kt, src/main/kotlin/com/stack/knowledge/domain/user/domain/constant/ApproveStatus.kt
ApproveStatus enum 변경
ApproveStatus enum에서 PENDING을 REJECT로 좀 더 의미에 맞게 변경 해주었습니다.
=> # 152 ApproveStatus enum 변경

src/main/kotlin/com/stack/knowledge/domain/solve/application/service/SolveMissionService.kt, src/main/kotlin/com/stack/knowledge/domain/solve/domain/Solve.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/entity/SolveJpaEntity.kt, src/main/kotlin/com/stack/knowledge/domain/solve/persistence/mapper/SolveMapper.kt, src/main/kotlin/com/stack/knowledge/domain/solve/presentation/data/request/SolveMissionRequest.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/service/QueryAllSignUpRequestedTeacherService.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/service/QueryScoringPageDetailsService.kt, src/main/kotlin/com/stack/knowledge/domain/user/presentation/data/response/AllSignUpRequestTeacherResponse.kt, src/main/kotlin/com/stack/knowledge/domain/user/presentation/data/response/ScoringDetailsResponse.kt
회원가입 요청 기능 userId 추가 반환
*회원가입 요청 기능에 userId를 추가로 반환 해주었습니다.
* solvation을 좀 더 의미에 맞게 solution으로 변경 해주었습니다.
=> # 153 회원가입 요청 기능 userId 추가 반환

src/main/resources/templets/mail.html
mail templet를 생성했습니다.
기존 선생님 가입 flow는 아래와 같습니다.
1. google로 로그인
2. 서비스 이용 실패
3. pending . . .
4. 주변 선생님이 수락했다고 전달
5. 서비스 이용 가능
언제 회원가입이 수락되었는지 알 수 없기 때문에 굉장히 곤란한 상황이 생깁니다.
따라서 사용자가 가입한 email로 유저 피드백을 전송하는 방향으로 이 문제를 해결합니다.
이를 위해 html로 유저 피드백이 가능한 메일 템플릿을 제작하였습니다.
제작된 html 파일을 가져가 사용하실 수 있습니다.
vs code의 경우, live server extention을 사용하여 편하게 테스트 하실 수 있습니다.
인텔리제이의 경우에는 아래와 같습니다.
1. HTML 파일을 IntelliJ에서 열기.
2. HTML 파일이 열린 상태에서 파일 내용이 표시되는 탭 상단에 있는 "Edit Configuration" 아이콘(연장선 형태의 톱니바퀴 모양)을 클릭합니다.
3. 나타나는 메뉴에서 "Edit Configurations..."를 선택합니다.
4. 좌측 상단에 있는 + 버튼을 클릭하고, 나오는 메뉴에서 "JavaScript Debug" 또는 "Static Web"을 선택합니다. (인텔리제이 버전에 따라 다를 수 있습니다)
5. "Name" 필드에 설정의 이름을 입력하고, "URL" 필드에는 HTML 파일의 경로를 입력합니다.
6. "OK" 버튼을 클릭하여 설정을 저장합니다.
7. 설정한 이름으로 돌아가서 우측 상단의 녹색 실행 버튼을 클릭하거나 Shift + F10 키를 눌러서 설정한 HTML 파일을 …
=> Add user feedback mail templet

src/main/kotlin/com/stack/knowledge/domain/auth/application/service/GoogleTeacherSignInService.kt, src/main/kotlin/com/stack/knowledge/domain/auth/exception/PendingUserException.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/service/QueryAllSignUpRequestedTeacherService.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/service/UpdateUserApproveStatusService.kt, src/main/kotlin/com/stack/knowledge/domain/user/domain/constant/ApproveStatus.kt, src/main/kotlin/com/stack/knowledge/domain/user/exception/InvalidApproveStatusException.kt, src/main/kotlin/com/stack/knowledge/domain/user/exception/RejectedUserException.kt, src/main/kotlin/com/stack/knowledge/global/error/ErrorCode.kt
Approve Status 상태 추가
* PENDING 상태를 추가 해주었습니다.
* REJECT -> REJECTED 로 수동적인 단어로 바꾸어 주었습니다.
* 그에 따른 변경 작업을 해주었습니다.
=> # 155 Approve Status 상태 추가

src/main/kotlin/com/stack/knowledge/domain/user/application/service/QueryScoringPageDetailsService.kt, src/main/kotlin/com/stack/knowledge/domain/user/presentation/data/response/ScoringDetailsResponse.kt
푼 문제 상세 조회 API 반환 인자 추가
content 인자를 추가로 반환해 주었습니다.
=> # 159 푼 문제 상세 조회 API 반환 인자 추가

src/main/kotlin/com/stack/knowledge/KnowledgeApplication.kt, src/main/kotlin/com/stack/knowledge/domain/solve/application/service/SolveMissionService.kt, src/main/kotlin/com/stack/knowledge/domain/time/exception/TimeLimitExceededException.kt, src/main/resources/templates/approval.html, src/main/resources/templates/reject.html
GAuth 관련 로직 삭제
GAuth 관련 로직 삭제
TimeLimitExceededException 삭제
=> # 163 GAuth 관련 로직 삭제

src/main/kotlin/com/stack/knowledge/domain/mission/application/service/QueryAllMissionService.kt, src/main/kotlin/com/stack/knowledge/domain/order/application/service/QueryIsOrderedOrderService.kt, src/main/kotlin/com/stack/knowledge/domain/student/application/service/QueryAllStudentsRankingService.kt, src/main/kotlin/com/stack/knowledge/domain/student/application/service/QueryStudentPointInfoService.kt, src/main/kotlin/com/stack/knowledge/domain/student/application/spi/QueryStudentPort.kt, src/main/kotlin/com/stack/knowledge/domain/student/persistence/StudentPersistenceAdapter.kt, src/main/kotlin/com/stack/knowledge/domain/student/persistence/repository/StudentJpaRepository.kt, src/main/kotlin/com/stack/knowledge/domain/student/presentation/data/response/StudentPointResponse.kt, src/main/kotlin/com/stack/knowledge/domain/user/application/service/QueryScoringPageService.kt, src/main/kotlin/com/stack/knowledge/domain/user/presentation/data/response/UserResponse.kt
내 정보 조회 API 반환 필드 추가
자신의 등수를 확인할 수 있는 필드를 반환하도록 추가했습니다.
=> # 166 내 정보 조회 API 반환 필드 추가

src/main/kotlin/com/stack/knowledge/common/service/GoogleService.kt, src/main/kotlin/com/stack/knowledge/domain/auth/application/service/GoogleStudentSignInService.kt, src/main/kotlin/com/stack/knowledge/domain/auth/application/service/GoogleTeacherSignInService.kt, src/main/kotlin/com/stack/knowledge/thirdparty/google/GoogleProperties.kt, src/main/resources/application.yml
Student/Teacher 구글 로그인 Redirect Url 분리
=> # 168 Student/Teacher 구글 로그인 Redirect Url 분리

src/main/kotlin/com/stack/knowledge/domain/auth/presentation/AuthWebAdapter.kt, src/main/kotlin/com/stack/knowledge/global/security/SecurityConfig.kt
=> # 170 set cookie 필드에 토큰 반환하는 API 추가

src/main/kotlin/com/stack/knowledge/domain/auth/presentation/AuthWebAdapter.kt, src/main/kotlin/com/stack/knowledge/global/config/WebMvcConfig.kt
Same Site 설정
ResponseCookie를 사용하여 Same Site를 설정했습니다.
=> # 172 Same Site 설정
